procedure InitializeComponent;
    begin
        self.button1 := new System.Windows.Forms.Button();
        self.button2 := new System.Windows.Forms.Button();
        self.button3 := new System.Windows.Forms.Button();
        self.button4 := new System.Windows.Forms.Button();
        self.button5 := new System.Windows.Forms.Button();
        self.button6 := new System.Windows.Forms.Button();
        self.button7 := new System.Windows.Forms.Button();
        self.button8 := new System.Windows.Forms.Button();
        self.button9 := new System.Windows.Forms.Button();
        self.button10 := new System.Windows.Forms.Button();
        self.button11 := new System.Windows.Forms.Button();
        self.button12 := new System.Windows.Forms.Button();
        self.button13 := new System.Windows.Forms.Button();
        self.button14 := new System.Windows.Forms.Button();
        self.button15 := new System.Windows.Forms.Button();
        self.button16 := new System.Windows.Forms.Button();
        self.button17 := new System.Windows.Forms.Button();
        self.button18 := new System.Windows.Forms.Button();
        self.button20 := new System.Windows.Forms.Button();
        self.button19 := new System.Windows.Forms.Button();
        self.button21 := new System.Windows.Forms.Button();
        self.button22 := new System.Windows.Forms.Button();
        self.button23 := new System.Windows.Forms.Button();
        self.button24 := new System.Windows.Forms.Button();
        self.button25 := new System.Windows.Forms.Button();
        self.button26 := new System.Windows.Forms.Button();
        self.button27 := new System.Windows.Forms.Button();
        self.button28 := new System.Windows.Forms.Button();
        self.button29 := new System.Windows.Forms.Button();
        self.label1 := new System.Windows.Forms.Label();
        self.textBox1 := new System.Windows.Forms.TextBox();
        self.label2 := new System.Windows.Forms.Label();
        self.textBox2 := new System.Windows.Forms.TextBox();
        self.button30 := new System.Windows.Forms.Button();
        self.button31 := new System.Windows.Forms.Button();
        self.button32 := new System.Windows.Forms.Button();
        self.button33 := new System.Windows.Forms.Button();
        self.button34 := new System.Windows.Forms.Button();
        self.button35 := new System.Windows.Forms.Button();
        self.button36 := new System.Windows.Forms.Button();
        self.button37 := new System.Windows.Forms.Button();
        self.button38 := new System.Windows.Forms.Button();
        self.button39 := new System.Windows.Forms.Button();
        self.button40 := new System.Windows.Forms.Button();
        self.button41 := new System.Windows.Forms.Button();
        self.button42 := new System.Windows.Forms.Button();
        self.button43 := new System.Windows.Forms.Button();
        self.button44 := new System.Windows.Forms.Button();
        self.button45 := new System.Windows.Forms.Button();
        self.button46 := new System.Windows.Forms.Button();
        self.button47 := new System.Windows.Forms.Button();
        self.button48 := new System.Windows.Forms.Button();
        self.button49 := new System.Windows.Forms.Button();
        self.button50 := new System.Windows.Forms.Button();
        self.button51 := new System.Windows.Forms.Button();
        self.button52 := new System.Windows.Forms.Button();
        self.button53 := new System.Windows.Forms.Button();
        self.button54 := new System.Windows.Forms.Button();
        self.button55 := new System.Windows.Forms.Button();
        self.button56 := new System.Windows.Forms.Button();
        self.button57 := new System.Windows.Forms.Button();
        self.button58 := new System.Windows.Forms.Button();
        self.richTextBox1 := new System.Windows.Forms.RichTextBox();
        self.button59 := new System.Windows.Forms.Button();
        self.label3 := new System.Windows.Forms.Label();
        self.textBox3 := new System.Windows.Forms.TextBox();
        self.button60 := new System.Windows.Forms.Button();
        self.label4 := new System.Windows.Forms.Label();
        self.textBox4 := new System.Windows.Forms.TextBox();
        self.label5 := new System.Windows.Forms.Label();
        self.SuspendLayout();
        // 
        // button1
        // 
        self.button1.BackColor := System.Drawing.SystemColors.ControlLight;
        self.button1.Location := new System.Drawing.Point(266, 54);
        self.button1.Name := 'button1';
        self.button1.Size := new System.Drawing.Size(45, 45);
        self.button1.TabIndex := 0;
        self.button1.Text := '1';
        self.button1.UseVisualStyleBackColor := false;
        self.button1.Click += button1_Click;
        // 
        // button2
        // 
        self.button2.BackColor := System.Drawing.SystemColors.ControlLight;
        self.button2.Location := new System.Drawing.Point(317, 54);
        self.button2.Name := 'button2';
        self.button2.Size := new System.Drawing.Size(45, 45);
        self.button2.TabIndex := 1;
        self.button2.Text := '2';
        self.button2.UseVisualStyleBackColor := false;
        self.button2.Click += button1_Click;
        // 
        // button3
        // 
        self.button3.Location := new System.Drawing.Point(368, 54);
        self.button3.Name := 'button3';
        self.button3.Size := new System.Drawing.Size(45, 45);
        self.button3.TabIndex := 2;
        self.button3.Text := '3';
        self.button3.UseVisualStyleBackColor := true;
        self.button3.Click += button1_Click;
        // 
        // button4
        // 
        self.button4.Location := new System.Drawing.Point(419, 54);
        self.button4.Name := 'button4';
        self.button4.Size := new System.Drawing.Size(45, 45);
        self.button4.TabIndex := 3;
        self.button4.Text := '4';
        self.button4.UseVisualStyleBackColor := true;
        self.button4.Click += button1_Click;
        // 
        // button5
        // 
        self.button5.Location := new System.Drawing.Point(470, 54);
        self.button5.Name := 'button5';
        self.button5.Size := new System.Drawing.Size(45, 45);
        self.button5.TabIndex := 4;
        self.button5.Text := '5';
        self.button5.UseVisualStyleBackColor := true;
        self.button5.Click += button1_Click;
        // 
        // button6
        // 
        self.button6.Location := new System.Drawing.Point(266, 105);
        self.button6.Name := 'button6';
        self.button6.Size := new System.Drawing.Size(45, 45);
        self.button6.TabIndex := 5;
        self.button6.Text := '6';
        self.button6.UseVisualStyleBackColor := true;
        self.button6.Click += button1_Click;
        // 
        // button7
        // 
        self.button7.Location := new System.Drawing.Point(317, 105);
        self.button7.Name := 'button7';
        self.button7.Size := new System.Drawing.Size(45, 45);
        self.button7.TabIndex := 6;
        self.button7.Text := '7';
        self.button7.UseVisualStyleBackColor := true;
        self.button7.Click += button1_Click;
        // 
        // button8
        // 
        self.button8.Location := new System.Drawing.Point(368, 105);
        self.button8.Name := 'button8';
        self.button8.Size := new System.Drawing.Size(45, 45);
        self.button8.TabIndex := 7;
        self.button8.Text := '8';
        self.button8.UseVisualStyleBackColor := true;
        self.button8.Click += button1_Click;
        // 
        // button9
        // 
        self.button9.Location := new System.Drawing.Point(419, 105);
        self.button9.Name := 'button9';
        self.button9.Size := new System.Drawing.Size(45, 45);
        self.button9.TabIndex := 8;
        self.button9.Text := '9';
        self.button9.UseVisualStyleBackColor := true;
        self.button9.Click += button1_Click;
        // 
        // button10
        // 
        self.button10.Location := new System.Drawing.Point(470, 105);
        self.button10.Name := 'button10';
        self.button10.Size := new System.Drawing.Size(45, 45);
        self.button10.TabIndex := 9;
        self.button10.Text := '10';
        self.button10.UseVisualStyleBackColor := true;
        self.button10.Click += button1_Click;
        // 
        // button11
        // 
        self.button11.Location := new System.Drawing.Point(266, 156);
        self.button11.Name := 'button11';
        self.button11.Size := new System.Drawing.Size(45, 45);
        self.button11.TabIndex := 10;
        self.button11.Text := '11';
        self.button11.UseVisualStyleBackColor := true;
        self.button11.Click += button1_Click;
        // 
        // button12
        // 
        self.button12.Location := new System.Drawing.Point(317, 156);
        self.button12.Name := 'button12';
        self.button12.Size := new System.Drawing.Size(45, 45);
        self.button12.TabIndex := 11;
        self.button12.Text := '12';
        self.button12.UseVisualStyleBackColor := true;
        self.button12.Click += button1_Click;
        // 
        // button13
        // 
        self.button13.Location := new System.Drawing.Point(368, 156);
        self.button13.Name := 'button13';
        self.button13.Size := new System.Drawing.Size(45, 45);
        self.button13.TabIndex := 12;
        self.button13.Text := '13';
        self.button13.UseVisualStyleBackColor := true;
        self.button13.Click += button1_Click;
        // 
        // button14
        // 
        self.button14.Location := new System.Drawing.Point(419, 156);
        self.button14.Name := 'button14';
        self.button14.Size := new System.Drawing.Size(45, 45);
        self.button14.TabIndex := 13;
        self.button14.Text := '14';
        self.button14.UseVisualStyleBackColor := true;
        self.button14.Click += button1_Click;
        // 
        // button15
        // 
        self.button15.Location := new System.Drawing.Point(470, 156);
        self.button15.Name := 'button15';
        self.button15.Size := new System.Drawing.Size(45, 45);
        self.button15.TabIndex := 14;
        self.button15.Text := '15';
        self.button15.UseVisualStyleBackColor := true;
        self.button15.Click += button1_Click;
        // 
        // button16
        // 
        self.button16.Location := new System.Drawing.Point(266, 207);
        self.button16.Name := 'button16';
        self.button16.Size := new System.Drawing.Size(45, 45);
        self.button16.TabIndex := 15;
        self.button16.Text := '16';
        self.button16.UseVisualStyleBackColor := true;
        self.button16.Click += button1_Click;
        // 
        // button17
        // 
        self.button17.Location := new System.Drawing.Point(317, 207);
        self.button17.Name := 'button17';
        self.button17.Size := new System.Drawing.Size(45, 45);
        self.button17.TabIndex := 16;
        self.button17.Text := '17';
        self.button17.UseVisualStyleBackColor := true;
        self.button17.Click += button1_Click;
        // 
        // button18
        // 
        self.button18.Location := new System.Drawing.Point(368, 207);
        self.button18.Name := 'button18';
        self.button18.Size := new System.Drawing.Size(45, 45);
        self.button18.TabIndex := 17;
        self.button18.Text := '18';
        self.button18.UseVisualStyleBackColor := true;
        self.button18.Click += button1_Click;
        // 
        // button20
        // 
        self.button20.Location := new System.Drawing.Point(470, 207);
        self.button20.Name := 'button20';
        self.button20.Size := new System.Drawing.Size(45, 45);
        self.button20.TabIndex := 19;
        self.button20.Text := '20';
        self.button20.UseVisualStyleBackColor := true;
        self.button20.Click += button1_Click;
        // 
        // button19
        // 
        self.button19.Location := new System.Drawing.Point(419, 207);
        self.button19.Name := 'button19';
        self.button19.Size := new System.Drawing.Size(45, 45);
        self.button19.TabIndex := 20;
        self.button19.Text := '19';
        self.button19.UseVisualStyleBackColor := true;
        self.button19.Click += button1_Click;
        // 
        // button21
        // 
        self.button21.Location := new System.Drawing.Point(266, 258);
        self.button21.Name := 'button21';
        self.button21.Size := new System.Drawing.Size(45, 45);
        self.button21.TabIndex := 21;
        self.button21.Text := '21';
        self.button21.UseVisualStyleBackColor := true;
        self.button21.Click += button1_Click;
        // 
        // button22
        // 
        self.button22.Location := new System.Drawing.Point(317, 258);
        self.button22.Name := 'button22';
        self.button22.Size := new System.Drawing.Size(45, 45);
        self.button22.TabIndex := 22;
        self.button22.Text := '22';
        self.button22.UseVisualStyleBackColor := true;
        self.button22.Click += button1_Click;
        // 
        // button23
        // 
        self.button23.Location := new System.Drawing.Point(368, 258);
        self.button23.Name := 'button23';
        self.button23.Size := new System.Drawing.Size(45, 45);
        self.button23.TabIndex := 23;
        self.button23.Text := '23';
        self.button23.UseVisualStyleBackColor := true;
        self.button23.Click += button1_Click;
        // 
        // button24
        // 
        self.button24.Location := new System.Drawing.Point(419, 258);
        self.button24.Name := 'button24';
        self.button24.Size := new System.Drawing.Size(45, 45);
        self.button24.TabIndex := 24;
        self.button24.Text := '24';
        self.button24.UseVisualStyleBackColor := true;
        self.button24.Click += button1_Click;
        // 
        // button25
        // 
        self.button25.Location := new System.Drawing.Point(470, 258);
        self.button25.Name := 'button25';
        self.button25.Size := new System.Drawing.Size(45, 45);
        self.button25.TabIndex := 25;
        self.button25.Text := '25';
        self.button25.UseVisualStyleBackColor := true;
        self.button25.Click += button1_Click;
        // 
        // button26
        // 
        self.button26.Location := new System.Drawing.Point(173, 420);
        self.button26.Name := 'button26';
        self.button26.Size := new System.Drawing.Size(35, 35);
        self.button26.TabIndex := 26;
        self.button26.Text := 'А';
        self.button26.UseVisualStyleBackColor := true;
        self.button26.Click += button26_Click;
        // 
        // button27
        // 
        self.button27.Location := new System.Drawing.Point(214, 420);
        self.button27.Name := 'button27';
        self.button27.Size := new System.Drawing.Size(35, 35);
        self.button27.TabIndex := 27;
        self.button27.Text := 'Б';
        self.button27.UseVisualStyleBackColor := true;
        self.button27.Click += button26_Click;
        // 
        // button28
        // 
        self.button28.Location := new System.Drawing.Point(255, 420);
        self.button28.Name := 'button28';
        self.button28.Size := new System.Drawing.Size(35, 35);
        self.button28.TabIndex := 28;
        self.button28.Text := 'В';
        self.button28.UseVisualStyleBackColor := true;
        self.button28.Click += button26_Click;
        // 
        // button29
        // 
        self.button29.Location := new System.Drawing.Point(296, 420);
        self.button29.Name := 'button29';
        self.button29.Size := new System.Drawing.Size(35, 35);
        self.button29.TabIndex := 29;
        self.button29.Text := 'Г';
        self.button29.UseVisualStyleBackColor := true;
        self.button29.Click += button26_Click;
        // 
        // label1
        // 
        self.label1.ForeColor := System.Drawing.Color.Yellow;
        self.label1.Location := new System.Drawing.Point(266, 327);
        self.label1.Name := 'label1';
        self.label1.Size := new System.Drawing.Size(249, 20);
        self.label1.TabIndex := 30;
        self.label1.Text := 'Введите номер поля для вставки буквы';
        // 
        // textBox1
        // 
        self.textBox1.Location := new System.Drawing.Point(316, 350);
        self.textBox1.Name := 'textBox1';
        self.textBox1.Size := new System.Drawing.Size(148, 20);
        self.textBox1.TabIndex := 31;
        // 
        // label2
        // 
        self.label2.ForeColor := System.Drawing.Color.Yellow;
        self.label2.Location := new System.Drawing.Point(266, 373);
        self.label2.Name := 'label2';
        self.label2.Size := new System.Drawing.Size(249, 20);
        self.label2.TabIndex := 32;
        // 
        // textBox2
        // 
        self.textBox2.Location := new System.Drawing.Point(551, 347);
        self.textBox2.Name := 'textBox2';
        self.textBox2.Size := new System.Drawing.Size(140, 20);
        self.textBox2.TabIndex := 33;
        // 
        // button30
        // 
        self.button30.Location := new System.Drawing.Point(337, 420);
        self.button30.Name := 'button30';
        self.button30.Size := new System.Drawing.Size(35, 35);
        self.button30.TabIndex := 34;
        self.button30.Text := 'Д';
        self.button30.UseVisualStyleBackColor := true;
        self.button30.Click += button26_Click;
        // 
        // button31
        // 
        self.button31.Location := new System.Drawing.Point(378, 420);
        self.button31.Name := 'button31';
        self.button31.Size := new System.Drawing.Size(35, 35);
        self.button31.TabIndex := 35;
        self.button31.Text := 'Е';
        self.button31.UseVisualStyleBackColor := true;
        self.button31.Click += button26_Click;
        // 
        // button32
        // 
        self.button32.Location := new System.Drawing.Point(419, 420);
        self.button32.Name := 'button32';
        self.button32.Size := new System.Drawing.Size(35, 35);
        self.button32.TabIndex := 36;
        self.button32.Text := 'Ё';
        self.button32.UseVisualStyleBackColor := true;
        self.button32.Click += button26_Click;
        // 
        // button33
        // 
        self.button33.Location := new System.Drawing.Point(460, 420);
        self.button33.Name := 'button33';
        self.button33.Size := new System.Drawing.Size(35, 35);
        self.button33.TabIndex := 37;
        self.button33.Text := 'Ж';
        self.button33.UseVisualStyleBackColor := true;
        self.button33.Click += button26_Click;
        // 
        // button34
        // 
        self.button34.Location := new System.Drawing.Point(501, 420);
        self.button34.Name := 'button34';
        self.button34.Size := new System.Drawing.Size(35, 35);
        self.button34.TabIndex := 38;
        self.button34.Text := 'З';
        self.button34.UseVisualStyleBackColor := true;
        self.button34.Click += button26_Click;
        // 
        // button35
        // 
        self.button35.Location := new System.Drawing.Point(542, 420);
        self.button35.Name := 'button35';
        self.button35.Size := new System.Drawing.Size(35, 35);
        self.button35.TabIndex := 39;
        self.button35.Text := 'И';
        self.button35.UseVisualStyleBackColor := true;
        self.button35.Click += button26_Click;
        // 
        // button36
        // 
        self.button36.Location := new System.Drawing.Point(583, 420);
        self.button36.Name := 'button36';
        self.button36.Size := new System.Drawing.Size(35, 35);
        self.button36.TabIndex := 40;
        self.button36.Text := 'Й';
        self.button36.UseVisualStyleBackColor := true;
        self.button36.Click += button26_Click;
        // 
        // button37
        // 
        self.button37.Location := new System.Drawing.Point(583, 461);
        self.button37.Name := 'button37';
        self.button37.Size := new System.Drawing.Size(35, 35);
        self.button37.TabIndex := 52;
        self.button37.Text := 'Ф';
        self.button37.UseVisualStyleBackColor := true;
        self.button37.Click += button26_Click;
        // 
        // button38
        // 
        self.button38.Location := new System.Drawing.Point(542, 461);
        self.button38.Name := 'button38';
        self.button38.Size := new System.Drawing.Size(35, 35);
        self.button38.TabIndex := 51;
        self.button38.Text := 'У';
        self.button38.UseVisualStyleBackColor := true;
        self.button38.Click += button26_Click;
        // 
        // button39
        // 
        self.button39.Location := new System.Drawing.Point(501, 461);
        self.button39.Name := 'button39';
        self.button39.Size := new System.Drawing.Size(35, 35);
        self.button39.TabIndex := 50;
        self.button39.Text := 'Т';
        self.button39.UseVisualStyleBackColor := true;
        self.button39.Click += button26_Click;
        // 
        // button40
        // 
        self.button40.Location := new System.Drawing.Point(460, 461);
        self.button40.Name := 'button40';
        self.button40.Size := new System.Drawing.Size(35, 35);
        self.button40.TabIndex := 49;
        self.button40.Text := 'С';
        self.button40.UseVisualStyleBackColor := true;
        self.button40.Click += button26_Click;
        // 
        // button41
        // 
        self.button41.Location := new System.Drawing.Point(419, 461);
        self.button41.Name := 'button41';
        self.button41.Size := new System.Drawing.Size(35, 35);
        self.button41.TabIndex := 48;
        self.button41.Text := 'Р';
        self.button41.UseVisualStyleBackColor := true;
        self.button41.Click += button26_Click;
        // 
        // button42
        // 
        self.button42.Location := new System.Drawing.Point(378, 461);
        self.button42.Name := 'button42';
        self.button42.Size := new System.Drawing.Size(35, 35);
        self.button42.TabIndex := 47;
        self.button42.Text := 'П';
        self.button42.UseVisualStyleBackColor := true;
        self.button42.Click += button26_Click;
        // 
        // button43
        // 
        self.button43.Location := new System.Drawing.Point(337, 461);
        self.button43.Name := 'button43';
        self.button43.Size := new System.Drawing.Size(35, 35);
        self.button43.TabIndex := 46;
        self.button43.Text := 'О';
        self.button43.UseVisualStyleBackColor := true;
        self.button43.Click += button26_Click;
        // 
        // button44
        // 
        self.button44.Location := new System.Drawing.Point(296, 461);
        self.button44.Name := 'button44';
        self.button44.Size := new System.Drawing.Size(35, 35);
        self.button44.TabIndex := 44;
        self.button44.Text := 'Н';
        self.button44.UseVisualStyleBackColor := true;
        self.button44.Click += button26_Click;
        // 
        // button45
        // 
        self.button45.Location := new System.Drawing.Point(255, 461);
        self.button45.Name := 'button45';
        self.button45.Size := new System.Drawing.Size(35, 35);
        self.button45.TabIndex := 43;
        self.button45.Text := 'М';
        self.button45.UseVisualStyleBackColor := true;
        self.button45.Click += button26_Click;
        // 
        // button46
        // 
        self.button46.Location := new System.Drawing.Point(214, 461);
        self.button46.Name := 'button46';
        self.button46.Size := new System.Drawing.Size(35, 35);
        self.button46.TabIndex := 42;
        self.button46.Text := 'Л';
        self.button46.UseVisualStyleBackColor := true;
        self.button46.Click += button26_Click;
        // 
        // button47
        // 
        self.button47.Location := new System.Drawing.Point(173, 461);
        self.button47.Name := 'button47';
        self.button47.Size := new System.Drawing.Size(35, 35);
        self.button47.TabIndex := 41;
        self.button47.Text := 'К';
        self.button47.UseVisualStyleBackColor := true;
        self.button47.Click += button26_Click;
        // 
        // button48
        // 
        self.button48.Location := new System.Drawing.Point(583, 502);
        self.button48.Name := 'button48';
        self.button48.Size := new System.Drawing.Size(35, 35);
        self.button48.TabIndex := 63;
        self.button48.Text := 'Я';
        self.button48.UseVisualStyleBackColor := true;
        self.button48.Click += button26_Click;
        // 
        // button49
        // 
        self.button49.Location := new System.Drawing.Point(542, 502);
        self.button49.Name := 'button49';
        self.button49.Size := new System.Drawing.Size(35, 35);
        self.button49.TabIndex := 62;
        self.button49.Text := 'Ю';
        self.button49.UseVisualStyleBackColor := true;
        self.button49.Click += button26_Click;
        // 
        // button50
        // 
        self.button50.Location := new System.Drawing.Point(501, 502);
        self.button50.Name := 'button50';
        self.button50.Size := new System.Drawing.Size(35, 35);
        self.button50.TabIndex := 61;
        self.button50.Text := 'Э';
        self.button50.UseVisualStyleBackColor := true;
        self.button50.Click += button26_Click;
        // 
        // button51
        // 
        self.button51.Location := new System.Drawing.Point(460, 502);
        self.button51.Name := 'button51';
        self.button51.Size := new System.Drawing.Size(35, 35);
        self.button51.TabIndex := 60;
        self.button51.Text := 'Ь';
        self.button51.UseVisualStyleBackColor := true;
        self.button51.Click += button26_Click;
        // 
        // button52
        // 
        self.button52.Location := new System.Drawing.Point(419, 502);
        self.button52.Name := 'button52';
        self.button52.Size := new System.Drawing.Size(35, 35);
        self.button52.TabIndex := 59;
        self.button52.Text := 'Ы';
        self.button52.UseVisualStyleBackColor := true;
        self.button52.Click += button26_Click;
        // 
        // button53
        // 
        self.button53.Location := new System.Drawing.Point(378, 502);
        self.button53.Name := 'button53';
        self.button53.Size := new System.Drawing.Size(35, 35);
        self.button53.TabIndex := 58;
        self.button53.Text := 'Ъ';
        self.button53.UseVisualStyleBackColor := true;
        self.button53.Click += button26_Click;
        // 
        // button54
        // 
        self.button54.Location := new System.Drawing.Point(337, 502);
        self.button54.Name := 'button54';
        self.button54.Size := new System.Drawing.Size(35, 35);
        self.button54.TabIndex := 57;
        self.button54.Text := 'Щ';
        self.button54.UseVisualStyleBackColor := true;
        self.button54.Click += button26_Click;
        // 
        // button55
        // 
        self.button55.Location := new System.Drawing.Point(296, 502);
        self.button55.Name := 'button55';
        self.button55.Size := new System.Drawing.Size(35, 35);
        self.button55.TabIndex := 56;
        self.button55.Text := 'Ш';
        self.button55.UseVisualStyleBackColor := true;
        self.button55.Click += button26_Click;
        // 
        // button56
        // 
        self.button56.Location := new System.Drawing.Point(255, 502);
        self.button56.Name := 'button56';
        self.button56.Size := new System.Drawing.Size(35, 35);
        self.button56.TabIndex := 55;
        self.button56.Text := 'Ч';
        self.button56.UseVisualStyleBackColor := true;
        self.button56.Click += button26_Click;
        // 
        // button57
        // 
        self.button57.Location := new System.Drawing.Point(214, 502);
        self.button57.Name := 'button57';
        self.button57.Size := new System.Drawing.Size(35, 35);
        self.button57.TabIndex := 54;
        self.button57.Text := 'Ц';
        self.button57.UseVisualStyleBackColor := true;
        self.button57.Click += button26_Click;
        // 
        // button58
        // 
        self.button58.Location := new System.Drawing.Point(173, 502);
        self.button58.Name := 'button58';
        self.button58.Size := new System.Drawing.Size(35, 35);
        self.button58.TabIndex := 53;
        self.button58.Text := 'Х';
        self.button58.UseVisualStyleBackColor := true;
        self.button58.Click += button26_Click;
        // 
        // richTextBox1
        // 
        self.richTextBox1.BackColor := System.Drawing.SystemColors.Control;
        self.richTextBox1.Font := new System.Drawing.Font('Times New Roman', 12, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.richTextBox1.Location := new System.Drawing.Point(12, 55);
        self.richTextBox1.Name := 'richTextBox1';
        self.richTextBox1.ReadOnly := true;
        self.richTextBox1.Size := new System.Drawing.Size(248, 337);
        self.richTextBox1.TabIndex := 64;
        self.richTextBox1.Text := '';
        // 
        // button59
        // 
        self.button59.Location := new System.Drawing.Point(551, 373);
        self.button59.Name := 'button59';
        self.button59.Size := new System.Drawing.Size(67, 26);
        self.button59.TabIndex := 65;
        self.button59.Text := 'Принять';
        self.button59.UseVisualStyleBackColor := true;
        self.button59.Click += button59_Click;
        // 
        // label3
        // 
        self.label3.ForeColor := System.Drawing.Color.Yellow;
        self.label3.Location := new System.Drawing.Point(559, 316);
        self.label3.Name := 'label3';
        self.label3.Size := new System.Drawing.Size(131, 25);
        self.label3.TabIndex := 66;
        // 
        // textBox3
        // 
        self.textBox3.Enabled := false;
        self.textBox3.Font := new System.Drawing.Font('Times New Roman', 10, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.textBox3.Location := new System.Drawing.Point(608, 54);
        self.textBox3.Name := 'textBox3';
        self.textBox3.Size := new System.Drawing.Size(70, 23);
        self.textBox3.TabIndex := 67;
        // 
        // button60
        // 
        self.button60.Location := new System.Drawing.Point(624, 373);
        self.button60.Name := 'button60';
        self.button60.Size := new System.Drawing.Size(67, 26);
        self.button60.TabIndex := 68;
        self.button60.Text := 'Сброс';
        self.button60.UseVisualStyleBackColor := true;
        self.button60.Click += button60_Click;
        // 
        // label4
        // 
        self.label4.ForeColor := System.Drawing.Color.Yellow;
        self.label4.Location := new System.Drawing.Point(551, 55);
        self.label4.Name := 'label4';
        self.label4.Size := new System.Drawing.Size(56, 23);
        self.label4.TabIndex := 69;
        self.label4.Text := 'Игрок 1';
        self.label4.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // textBox4
        // 
        self.textBox4.Enabled := false;
        self.textBox4.Font := new System.Drawing.Font('Times New Roman', 10, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, (System.Byte(204)));
        self.textBox4.Location := new System.Drawing.Point(608, 88);
        self.textBox4.Name := 'textBox4';
        self.textBox4.Size := new System.Drawing.Size(70, 23);
        self.textBox4.TabIndex := 70;
        // 
        // label5
        // 
        self.label5.ForeColor := System.Drawing.Color.Yellow;
        self.label5.Location := new System.Drawing.Point(551, 88);
        self.label5.Name := 'label5';
        self.label5.Size := new System.Drawing.Size(56, 23);
        self.label5.TabIndex := 71;
        self.label5.Text := 'Игрок 2';
        self.label5.TextAlign := System.Drawing.ContentAlignment.MiddleCenter;
        // 
        // Form1
        // 
        self.AutoScaleMode := System.Windows.Forms.AutoScaleMode.Inherit;
        self.AutoValidate := System.Windows.Forms.AutoValidate.EnablePreventFocusChange;
        self.BackColor := System.Drawing.Color.ForestGreen;
        self.ClientSize := new System.Drawing.Size(721, 564);
        self.Controls.Add(self.label5);
        self.Controls.Add(self.textBox4);
        self.Controls.Add(self.label4);
        self.Controls.Add(self.button60);
        self.Controls.Add(self.textBox3);
        self.Controls.Add(self.label3);
        self.Controls.Add(self.button59);
        self.Controls.Add(self.richTextBox1);
        self.Controls.Add(self.button48);
        self.Controls.Add(self.button49);
        self.Controls.Add(self.button50);
        self.Controls.Add(self.button51);
        self.Controls.Add(self.button52);
        self.Controls.Add(self.button53);
        self.Controls.Add(self.button54);
        self.Controls.Add(self.button55);
        self.Controls.Add(self.button56);
        self.Controls.Add(self.button57);
        self.Controls.Add(self.button58);
        self.Controls.Add(self.button37);
        self.Controls.Add(self.button38);
        self.Controls.Add(self.button39);
        self.Controls.Add(self.button40);
        self.Controls.Add(self.button41);
        self.Controls.Add(self.button42);
        self.Controls.Add(self.button43);
        self.Controls.Add(self.button44);
        self.Controls.Add(self.button45);
        self.Controls.Add(self.button46);
        self.Controls.Add(self.button47);
        self.Controls.Add(self.button36);
        self.Controls.Add(self.button35);
        self.Controls.Add(self.button34);
        self.Controls.Add(self.button33);
        self.Controls.Add(self.button32);
        self.Controls.Add(self.button31);
        self.Controls.Add(self.button30);
        self.Controls.Add(self.textBox2);
        self.Controls.Add(self.label2);
        self.Controls.Add(self.textBox1);
        self.Controls.Add(self.label1);
        self.Controls.Add(self.button29);
        self.Controls.Add(self.button28);
        self.Controls.Add(self.button27);
        self.Controls.Add(self.button26);
        self.Controls.Add(self.button25);
        self.Controls.Add(self.button24);
        self.Controls.Add(self.button23);
        self.Controls.Add(self.button22);
        self.Controls.Add(self.button21);
        self.Controls.Add(self.button19);
        self.Controls.Add(self.button20);
        self.Controls.Add(self.button18);
        self.Controls.Add(self.button17);
        self.Controls.Add(self.button16);
        self.Controls.Add(self.button15);
        self.Controls.Add(self.button14);
        self.Controls.Add(self.button13);
        self.Controls.Add(self.button12);
        self.Controls.Add(self.button11);
        self.Controls.Add(self.button10);
        self.Controls.Add(self.button9);
        self.Controls.Add(self.button8);
        self.Controls.Add(self.button7);
        self.Controls.Add(self.button6);
        self.Controls.Add(self.button5);
        self.Controls.Add(self.button4);
        self.Controls.Add(self.button3);
        self.Controls.Add(self.button2);
        self.Controls.Add(self.button1);
        self.Name := 'Form1';
        self.Text := 'Form1';
        self.Load += Form1_Load;
        self.ResumeLayout(false);
        self.PerformLayout();
    end;
